#:schema node_modules/wrangler/config-schema.json
name = "flight-check"
main = "source/index.ts"
compatibility_date = "2024-12-12"
workers_dev = false
routes = [{ pattern = "flight-check.thatskyapplication.com", custom_domain = true }]

[triggers]
crons = ["*/5 * * * *"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "FLIGHT_CHECK"
id = "2fb2cc39984147d9bcd7c08ac6c49b7e"
